config/routes.rb
Rails.application.routes.draw do
  get 'assignments/create'
  post 'assignments/update'
  get 'assignments/show'
  get 'todos/index'
  devise_for :users, controllers:{
    registrations: 'user/registrations'
  }
  root to: 'todos#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assignment.rb
class Assignment < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord

  has_many :assignments
  has_many :users, through: :assignments

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assignments, dependent: :destroy
  has_many :todos, through: :assignments
  after_create :load_todos

  private

  def load_todos
    @todos = Todo.all
    @user = User.last
    @assignments = []
    @todos.each do |todo|
      @user.assignments << Assignment.new(user: @user, todo: todo)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assignments_controller.rb
class AssignmentsController < ApplicationController
before_action :completed_todos, only: [:show, :updated]
before_action :authenticate_user!

  def create
    @todos = Todo.all
    @user = current_user
    @assignments = []
    @todos.each do |todo|
      @user.assignments << Assignment.new(user: current_user, todo: todo)
    end
    redirect_to root_path
  end

  def update
    @assignment = Assignment.find(params[:assignment_id])
    if  @assignment.completed?
      @assignment.completed = false
    else
      @assignment.completed = true
    end
    @assignment.save
    redirect_to root_path
  end

  def show
    @assignment = Assignment.find(params[:assignment_id])
    @todo = @assignment.todo
    @users = User.joins(:assignments).where(assignments: {completed: true, todo: @todo}).order('name ASC')
    @ranking = Assignment.joins(:todo).where(assignments: {completed: true, todo: @todo}).order('updated_at ASC').limit(5)
  end

  def completed_todos
    @todos = Todo.all
    @assignments = current_user.assignments
    @completed_todos = current_user.assignments.where(completed: true).count
  end


end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
before_action :authenticate_user!

  def index
    @todos = Todo.all
    @assignments = current_user.assignments
    @completed_todos = current_user.assignments.where(completed: true).count
  end
end

app/controllers/user/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/user/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/user/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def editname
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

 protected

  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :photo])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  #def after_sign_up_path_for(resource)
  #   assignments_create_path()
  #end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assignments_helper.rb
module AssignmentsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/assignments/show.html.erb
<div class="container">
  <div class="row">

    <div class="p-1 col-12 col-sm-6 container">
      <h4>Users who have completed <%= @todo.title %>:</h4>
      <br>
      <% @users.each do |user| %>
      <li><%= user.name %></li>
      <% end %>
    </div>

    <div class="p-1 col-12 col-sm-6 container">
      <h4>Ranking:</h4>
      <br>
      <ol type="1">


      <% @ranking.each do |assign| %>
      <li>
      <div class="card col-9 p-2 m-3">
        <%= assign.user.name %>
        <%= image_tag assign.user.photo, class:'card-img-top' %>
      </div>
      </li>
      <% end %>
      </ol>
    </div>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>

  <body>

    <%= render 'shared/navbar' %>

    <div class="container">
        <%= yield %>
    </div>

  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<%= root_path %> ">Todo 18!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="navbar-nav mr-auto">
        <% if user_signed_in? %>
          Tasks completed: <%= @completed_todos %>/<%=@assignments.count %>
        <% end %>
    </ul>

    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li>Welcome, <%= current_user.name %>   <a class="btn btn-info" href="<%= destroy_user_session_path %>" data-method="DELETE">Log out</a></li>
      <% else %>
        <li><a class="btn btn-info" href="<%= new_user_registration_path %>">Sign Up</a></li>
      <% end %>
    </ul>

  </div>
</nav>

app/views/todos/index.html.erb
<div class="container">


  <div class="row">

    <% @assignments.each do |assignment|%>
      <div class="mx-auto col-10 col-md-4">
        <div class="card p-2 m-3    ">

          <td><%= assignment.todo.title %><td>

          <% if assignment.completed? %>
            <%= link_to assignments_show_path(:params => {:assignment_id => assignment.id}) do %>
               <%= image_tag assignment.todo.photo, class: 'card-img-top' %>
            <% end %>
            <button class="btn btn-sm btn-danger"><%= link_to 'Uncomplete', assignments_update_path(:params => {:assignment_id => assignment.id}), method: :post %></button>
          <% else %>
            <%= link_to assignments_show_path(:params => {:assignment_id => assignment.id}) do %>
             <%= image_tag assignment.todo.photo, class: 'card-img-top gray' %>
            <% end %>
            <td>
              <button class="btn btn-sm btn-info"><%= link_to 'Complete', assignments_update_path(:params => {:assignment_id => assignment.id}), method: :post %></button>
            </td>
          <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>